baseurl      = "localhost"
title        = "Danabases"
languageCode = "en-us"
theme        = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A simple and beautiful blog"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "Danabases blog"
  keywords = "homepage, blog"
  images = [""]

  # Custom footer
  [params.footer]
    trademark = 2025
    rss = false
    copyright = false

  [[params.social]]
    url  = "https://github.com/d-bits"
    icon = "/assets/pics/svgs/github.svg"

  [[params.social]]
      url   = "https://linkedin.com/danabases"
      icon  = "/assets/pics/svgs/linkedin.svg"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Danabases"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

#  [languages.en.params]
#    subtitle  = "A simple theme for Hugo"

    [languages.en.params.logo]
      logoText = "Danabases"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "skills"
    name       = "Skills"
    url        = "/skills"
  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"    

[pagination]
  pagerSize = 15
  path = "page"
  disableAliases = false
