[build]
  publish = "public"
  command = """\
  curl -sLJO "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  tar -C "${HOME}/.local" -xf "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  rm "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  export PATH="${HOME}/.local/dart-sass:${PATH}" && \
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}"
  """

[build.environment]
DART_SASS_VERSION = "1.48.2"
GO_VERSION = "1.25.0"
HUGO_VERSION = "0.149.0"
NODE_VERSION = "22.18.0"
TZ = "Europe/Oslo"

[context.production.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.148.2"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.148.2"

[context.next.environment]
  HUGO_VERSION = "0.148.2"
