backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/pics
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'publishdate', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'select', multiple: true,  options: ["python", "sql", "automation", "docker", "other"]}
      - { label: 'Draft', name: 'draft', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

# Enable saving drafts
publish_mode: editorial_workflow